### PR TITLE
Introduce the way to overwrite metadata without modifying Cargo.toml original metadata

### PR DESCRIPTION
**Pull request by cat-in-136**
Provides a way to temporarily or permanently override the cargo-generate-rpm setting in `[package.metadata.generate-rpm]` in Cargo.toml with a separate file, separate table, or CLI option.

There were similar requests such as #18 (variants), #19 (temp version), #31 (seems to be sub-package) and #35 (temp release). This PR intend to prepare internal structure for these requests and most of these would be resolved by this PR.

* [x] replace rpm configuration with the "compound metadata"
* [x] add way to overwrite using external file: `--???=external.toml`
* [x] add way to overwrite using cli inline TOML: `--???='release = "128"'`
* [x] add sub-path of TOML to support variant
* [x] add convenience argument: `--variant=NAME` and `[package.metadata.generate-rpm.variants.NAME]`
* [x] modify README.md

I am not expected to do without the `[package.metadata.generate-rpm]` in Cargo.toml.

### CODE REVIEW

**Comment by cat-in-136** [comment]
FYI: I have not write "way to overwrite using cli inline TOML" on my metadata-overwrite branch today, but if you are a zsh user, you can use `--metadata-overwrite=<(echo 'release = "128"')`.

**Comment by ximon18** [comment]
FYI I did some simplistic local testing of this branch by passing `--metadata-overwrite-inline 'version="xxx"'` and that seemed to do as desired, i.e. I no longer need to edit the `Cargo.toml` file in order to control the value of `version` when building the RPM package. I've also prepared a [PR for one of our projects](https://github.com/NLnetLabs/routinator/pull/759) to use the new feature which also seems to work, though will be kept as a draft PR until this feature is released at which point I can go back and update the PR to use the release version of `cargo-generate-rpm`.

**Comment by cat-in-136** [comment]
@ximon18 Thank you for confirmation. But I have changed `--metadata-overwrite-inline` to `--set-metadata` or `-s`. Because the former name `--metadata-overwrite-inline` is too long. Please follow the change.

**Comment by ximon18** [comment]
> @ximon18 Thank you for confirmation. But I have changed `--metadata-overwrite-inline` to `--set-metadata` or `-s`. Because the former name `--metadata-overwrite-inline` is too long. Please follow the change.

The [GH Action run](https://github.com/NLnetLabs/routinator/actions/runs/2821179969) in my own project that tests this feature ran without error after adjusting it to use the `--set-metadata` command line argument.

**Pull request merged**
